### ISSUE TITLE
fix path changelod

### ISSUE THREAD

**Issue by obar1** [obar1/0to100#22]
from another folder

```
(base) √ https-learning.oreilly.com.git % create_section https://learning.oreilly.com/library/view/official-google-cloud/9781119618430/
Traceback (most recent call last):
  File "/Users/mamat/git/obar1/https-learning.oreilly.com.git/0to100-latest/zero_to_one_hundred/main.py", line 34, in <module>
    run_main(sys.argv[1:])
  File "/Users/mamat/git/obar1/https-learning.oreilly.com.git/0to100-latest/zero_to_one_hundred/main.py", line 26, in run_main
    get_version()
  File "/Users/mamat/git/obar1/https-learning.oreilly.com.git/0to100-latest/zero_to_one_hundred/main.py", line 17, in get_version
    with open(change_log, mode="r", encoding="UTF-8") as file_change_log:
FileNotFoundError: [Errno 2] No such file or directory: 'changelog.md'
```

**Comment by obar1** [comment]
build actual path when reading the file
